server:
  port: 8770

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order_micro
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE    
  config:
    import:
    - configserver:http://localhost:9292  
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
  
     
    
   